version: "3"
services:
  usaver:
    build: .
    ports:
      - "8080:80"
      - "44462:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "44462"
      ASPNETCORE_ENVIRONMENT: "Production"
    volumes:
      - ${PWD}/appsettings.json:/App/appsettings.json
