name: Deployment to prod

on:
  push: 
    branches:
    - master
  workflow_dispatch:

jobs:
  conditional_job:
    if: ${{ !startsWith(github.event.head_commit.message,'%no-action%') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: Head commit message
      run: echo "${{ github.event.head_commit.message }}"
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Setup environment
      run: cd ./app && dotnet user-secrets set "DB:User" "saver" && dotnet user-secrets set "DB:Name" "saver" && dotnet user-secrets set "DB:Password" "${{ secrets.MASTER_DB_PASSWORD }}"
    - name: Warren - .NET Migrations
      uses: warrenbrasil/dotnet-migrations@v1
      with:
        project-path: ./app
        startup-project-path: ./app
        context: AppDatabaseContext
        connection: ${{ secrets.MASTER_CONNECTION_STRING }}
    - name: Setup Prod backend URL
      run: printf "const URL = '${{ secrets.URL }}';\nexport default URL;" > ./app/ClientApp/src/appUrl.js
    - name: Publish to directory
      run: dotnet publish -o ~/saver
    - name: Stop running service
      uses: fifsky/ssh-action@v0.0.6
      with:
        command: sudo service saver stop
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.USER }}
        server: ${{ secrets.SERVER }}
        port: ${{ secrets.PORT }}
        ssh_private_key: ${{ secrets.KEY }}
        local_path: ~/saver
        remote_path: /opt/saver
        sftp_only: true
        delete_remote_files: false
    - name: Start service
      uses: fifsky/ssh-action@v0.0.6
      with:
        command: sudo service saver start
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
      
