name: Deployment to prod

on:
  push: 
    branches:
    - master
  workflow_dispatch:

jobs:
  conditional_job:
    if: ${{ !startsWith(github.event.head_commit.message,'%no-action%') || github.event_name == 'workflow_dispatch' }}
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
    - name: Head commit message
      run: echo "${{ github.event.head_commit.message }}"
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Setup environment
      run: cd ./app && dotnet user-secrets set "DB:User" "saver" && dotnet user-secrets set "DB:Name" "saver" && dotnet user-secrets set "DB:Password" "${{ secrets.MASTER_DB_PASSWORD }}"
    - name: Warren - .NET Migrations
      uses: warrenbrasil/dotnet-migrations@v1
      with:
        project-path: ./app
        startup-project-path: ./app
        context: AppDatabaseContext
        connection: ${{ secrets.MASTER_CONNECTION_STRING }}
    - name: Setup Prod backend URL
      run: printf "const URL = '${{ secrets.URL }}';\nexport default URL;\n" > ./app/ClientApp/src/appUrl.js
    - name: Publish to directory
      env:
        CI: false
      run: dotnet publish -o ./saver
    - name: Setup DB Connection
      run: printf "${{ secrets.MASTER_DB_PASSWORD }}" > ./saver/creds
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.USER }}
        server: ${{ secrets.SERVER }}
        port: ${{ secrets.PORT }}
        ssh_private_key: ${{ secrets.KEY }}
        local_path: ./saver
        remote_path: /opt/saver/app
        sftp_only: true
        delete_remote_files: true
      
